#!/usr/bin/env node
/**
 * Regenerates assets/fonts/*.woff2 and assets/css/fonts.css from Google Fonts.
 *
 *     node tools/build-fonts.js
 *
 * You only need this if you change a font family. The generated files are
 * committed, so a normal checkout needs no build step and makes no external
 * requests, which is the whole point of self-hosting them.
 *
 * Only the Latin and Latin-Extended subsets are kept (this is an
 * English-language invitation) and identical variable-font files served for
 * several weights are stored once, declared with a font-weight *range*.
 */

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const ROOT      = path.join(__dirname, '..');
const FONT_DIR  = path.join(ROOT, 'assets/fonts');
const CSS_FILE  = path.join(ROOT, 'assets/css/fonts.css');

const FAMILIES = [
  { query: 'Great+Vibes',                          name: 'Great Vibes',        slug: 'great-vibes',        weights: ['400'] },
  { query: 'Jost:wght@300;400;500;600',            name: 'Jost',               slug: 'jost',               weights: ['300', '400', '500', '600'] },
  { query: 'Cormorant+Garamond:wght@300;400;500;600', name: 'Cormorant Garamond', slug: 'cormorant-garamond', weights: ['300', '400', '500', '600'] },
];

const SUBSETS = new Set(['latin', 'latin-ext']);

function curl(url, outFile) {
  const args = ['-sSL', '--max-time', '60', '-A', UA, url];
  if (outFile) { args.push('-o', outFile); execFileSync('curl', args); return null; }
  return execFileSync('curl', args, { maxBuffer: 1 << 26 }).toString();
}

fs.mkdirSync(FONT_DIR, { recursive: true });

const blocks = [];

for (const fam of FAMILIES) {
  const src = curl(`https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`);

  // One @font-face block per (weight, subset). Group them by subset so we can
  // spot the case where every weight is byte-identical (a variable font).
  const bySubset = new Map();

  for (const chunk of src.split('/*').slice(1)) {
    const subset = chunk.slice(0, chunk.indexOf('*/')).trim();
    if (!SUBSETS.has(subset)) continue;

    const url    = (chunk.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    const range  = (chunk.match(/unicode-range:\s*([^;]+);/) || [])[1];
    const weight = (chunk.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
    if (!url) continue;

    if (!bySubset.has(subset)) bySubset.set(subset, { range: range.trim(), entries: [] });
    bySubset.get(subset).entries.push({ weight, url });
  }

  for (const [subset, { range, entries }] of bySubset) {
    const buffers = entries.map(e => execFileSync('curl',
      ['-sSL', '--max-time', '60', '-A', UA, e.url], { maxBuffer: 1 << 26 }));

    const identical = buffers.every(b => b.equals(buffers[0]));
    const file = `${fam.slug}-${subset}.woff2`;

    if (!identical && entries.length > 1) {
      // Static per-weight faces: keep them separate.
      entries.forEach((e, i) => {
        const f = `${fam.slug}-${e.weight}-${subset}.woff2`;
        fs.writeFileSync(path.join(FONT_DIR, f), buffers[i]);
        blocks.push(face(fam.name, e.weight, f, range));
      });
      continue;
    }

    fs.writeFileSync(path.join(FONT_DIR, file), buffers[0]);
    const ws = fam.weights;
    const weight = ws.length > 1 ? `${ws[0]} ${ws[ws.length - 1]}` : ws[0];
    blocks.push(face(fam.name, weight, file, range));
    console.log(`${file}: ${(buffers[0].length / 1024).toFixed(0)} KB` +
                (entries.length > 1 ? `  (one variable file for ${weight})` : ''));
  }
}

function face(name, weight, file, range) {
  return `@font-face{font-family:'${name}';font-style:normal;font-weight:${weight};` +
         `font-display:swap;src:url('../fonts/${file}') format('woff2');` +
         `unicode-range:${range};}`;
}

const header = [
  '/* Self-hosted fonts: no external requests, no CDN dependency.',
  '   Latin + Latin-Extended subsets only.',
  '   Jost and Cormorant Garamond are variable fonts: one file each covers',
  '   the whole 300–600 weight range, hence the range in font-weight.',
  '',
  '   Great Vibes, Jost and Cormorant Garamond are licensed under the SIL',
  '   Open Font License 1.1. See assets/fonts/OFL.txt.',
  '',
  '   Generated by tools/build-fonts.js. Regenerate rather than hand-edit. */',
  ''
].join('\n');

fs.writeFileSync(CSS_FILE, header + '\n' + blocks.join('\n') + '\n');
console.log('\nwrote assets/css/fonts.css');
